import { cn } from '@/lib/utils';
import { Check, Sparkles, Database, AlertTriangle } from 'lucide-react';

export type DataSource = 'yahoo' | 'yahoo-query' | 'fmp' | 'ai' | 'scraping' | 'polygon';

interface DataSourceBadgeProps {
  source: DataSource;
  confidence?: number; // AI confidence score (0-1)
  className?: string;
}

const sourceConfig = {
  yahoo: {
    label: 'Yahoo Finance',
    icon: Check,
    className: 'bg-green-100 text-green-800 border-green-200',
    description: 'Live data from Yahoo Finance'
  },
  'yahoo-query': {
    label: 'Yahoo API',
    icon: Check,
    className: 'bg-green-100 text-green-800 border-green-200',
    description: 'Yahoo Finance Query API'
  },
  fmp: {
    label: 'FMP API',
    icon: Database,
    className: 'bg-blue-100 text-blue-800 border-blue-200',
    description: 'Financial Modeling Prep API'
  },
  ai: {
    label: 'AI-Sourced',
    icon: Sparkles,
    className: 'bg-purple-100 text-purple-800 border-purple-200',
    description: 'Generated by AI when traditional sources unavailable'
  },
  scraping: {
    label: 'Web Scraping',
    icon: Database,
    className: 'bg-gray-100 text-gray-800 border-gray-200',
    description: 'Scraped from financial websites'
  },
  polygon: {
    label: 'Polygon',
    icon: Database,
    className: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    description: 'Polygon.io API'
  }
};

export function DataSourceBadge({ source, confidence, className }: DataSourceBadgeProps) {
  const config = sourceConfig[source];
  const Icon = config.icon;
  const showWarning = source === 'ai' && confidence && confidence < 0.9;

  return (
    <div className="inline-flex items-center gap-1">
      <span
        className={cn(
          'inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium border',
          config.className,
          className
        )}
        title={config.description}
      >
        <Icon className="w-3 h-3" />
        {config.label}
      </span>

      {showWarning && (
        <span
          className="inline-flex items-center text-yellow-600"
          title={`Confidence: ${((confidence || 0) * 100).toFixed(0)}%`}
        >
          <AlertTriangle className="w-3.5 h-3.5" />
        </span>
      )}

      {source === 'ai' && confidence && (
        <span className="text-xs text-gray-500">
          ({((confidence || 0) * 100).toFixed(0)}%)
        </span>
      )}
    </div>
  );
}
